name: dart_app_deployer
version: 0.0.1
description: A daemon that listens to GitHub push webhook and that auto-redeploys the app.
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  dart_config: any
  shelf: any
  grinder: any
dev_dependencies:
  test: any